bbs/models.py
import datetime
from flask.ext.sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    author_name = db.Column(db.Unicode(20), nullable=False)
    title = db.Column(db.Unicode(100), nullable=False)
    body = db.Column(db.UnicodeText, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
    views = db.Column(db.Integer, nullable=False, default=0)

bbs/__init__.py
import flask
from bbs import views
from bbs.models import db

def create_app():
    app = flask.Flask(__name__, instance_relative_config=True)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    views.init_app(app)
    return app

bbs/views.py
import datetime
import flask
from bbs import models

def init_app(app):
    app.register_blueprint(board)

    # The trailing parenthesises make the filter name
    # same with the function name (`static`).
    @app.template_filter()
    def static(filename):
        # We don't use `url_for('static')` directly.
        # It's hard to override the default URL generation.
        # Sometimes you will need to change the host to CDN, for example.
        # TODO: consider static files per blueprint.
        return flask.url_for('static', filename=filename)

board = flask.Blueprint('board', __name__)

@board.route('/')
def index():
    page = flask.request.args.get('page', default=1, type=int)
    posts = models.Post.query.order_by(models.Post.id.desc())
    paging = posts.paginate(page)
    return flask.render_template('list.html', paging=paging)

@board.route('/posts/new')
def write():
    return flask.render_template('write.html')

@board.route('/posts/new', methods=['POST'])
def write_save():
    # TODO: use library for validation (WTForms or FormEncode)
    form = flask.request.form
    post = models.Post()
    post.author_name = form['author_name']
    post.title = form['title']
    post.body = form['body']

    models.db.session.add(post)
    models.db.session.commit()

    # `post.id` has been populated after the flush.
    # (`commit` implies `flush`)
    rv = flask.redirect(flask.url_for('.show', id=post.id))

    # Make sure that `rv` is a `flask.Request` instance.
    rv = flask.make_response(rv)
    # Set the name cookie
    age = datetime.timedelta(days=30).total_seconds()
    rv.set_cookie('author_name', post.author_name, max_age=age)

    return rv

@board.route('/posts/<int:id>')
def show(id):
    post = models.Post.query.get_or_404(id)
    return flask.render_template('show.html', post=post)

@board.app_template_filter()
def post_body(post):
    return post.body

bbs/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="{{ 'css/bootstrap.min.css'|static }}" rel="stylesheet" media="screen">
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <a href="{{ url_for('board.index') }}" class="brand">Board</a>
                </div>
            </div>

            {% block content %}{% endblock %}
        </div>
    </body>
</html>

bbs/templates/list.html
{% extends 'base.html' %}

{% block title %}List{% endblock %}

{% block content %}
<table class="table table-bordered">
    <tr>
        <th>Author</th>
        <th>Title</th>
        <th>Date</th>
    </tr>
{% for post in paging.items %}
    <tr>
        <td>{{ post.author_name }}</td>
        <td><a href="{{ url_for('board.show', id=post.id) }}">{{ post.title }}</a></td>
        <td>{{ post.created_at }}</td>
    </tr>
{% else %}
    <tr>
        <td colspan="3">No posts yet.</td>
    </tr>
{% endfor %}
</table>

<div class="pagination pull-left">
<ul>
{%- for page in paging.iter_pages() %}
    {% if page %}
    {% if page != paging.page %}
    <li><a href="{{ url_for('board.list', page=page) }}">{{ page }}</a></li>
    {% else %}
    <li class="active"><span>{{ page }}</span></li>
    {% endif %}
    {% else %}
    <li><span>…</span></li>
    {% endif %}
{%- endfor %}
</ul>
</div>

<p class="pull-right">
    <a href="{{ url_for('board.write') }}" class="btn btn-primary"><i class="icon-pencil icon-white"></i> New Post</a>
</p>
{% endblock %}

bbs/templates/show.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h2>{{ post.title }} <small>by {{ post.author_name }} @ {{ post.created_at }}</small></h2>
<hr>
{{ post|post_body }}
{% endblock %}

bbs/templates/write.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock %}

{% block content %}
<h2>New Post</h2>

<form method="post" action="{{ url_for('board.write_save') }}">
    <label>Author Name</label>
    {#-
        1. You can use `request` context local in the template.
        2. Jinja2 tries to access dict key if no attribute is found.
    #}
    <input type="text" name="author_name" value="{{ request.cookies.author_name }}" required>

    <label>Title</label>
    <input type="text" name="title" class="input-xxlarge" required>

    <label>Post Body</label>
    <textarea name="body" class="input-xxlarge" rows="6" required></textarea>

    <div class="form-actions">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>
{% endblock %}